// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package demo.msa.grpc.hello.api;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.msa.grpc.hello.api.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
