// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package demo.msa.grpc.hello.api;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_msa_grpc_hello_api_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_msa_grpc_hello_api_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_msa_grpc_hello_api_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_msa_grpc_hello_api_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\027demo.msa.grpc.hello.api\"\034" +
      "\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\" \n\rHelloRes" +
      "ponse\022\017\n\007message\030\001 \001(\t2f\n\014HelloService\022V" +
      "\n\003Say\022%.demo.msa.grpc.hello.api.HelloReq" +
      "uest\032&.demo.msa.grpc.hello.api.HelloResp" +
      "onse\"\000B\'\n\027demo.msa.grpc.hello.apiB\nHello" +
      "ProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_msa_grpc_hello_api_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_msa_grpc_hello_api_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_msa_grpc_hello_api_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_demo_msa_grpc_hello_api_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_msa_grpc_hello_api_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_msa_grpc_hello_api_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
